// Assets
import logo1 from "Assets/Images/SampleLogos/1.svg";
import logo2 from "Assets/Images/SampleLogos/2.png";
import logo3 from "Assets/Images/SampleLogos/3.svg";
import logo4 from "Assets/Images/SampleLogos/4.png";

export const featuredStartUps = [
    {
        projectName: "",
        projectDescription: "",
        projectLogo: logo1,
        currentFunding: 1000,
        fundingGoal: 1400,
        learnButtonLink: "/1",
        giveButtonLink: "/1",
        id: 1,
    },
    {
        projectName: "",
        projectDescription: "",
        projectLogo: logo2,
        currentFunding: 130000,
        fundingGoal: 190000,
        learnButtonLink: "/2",
        giveButtonLink: "/2",
        id: 2,
    },
    {
        projectName: "",
        projectDescription: "",
        projectLogo: logo3,
        currentFunding: 800,
        fundingGoal: 1800,
        learnButtonLink: "/3",
        giveButtonLink: "/3",
        id: 3,
    },
    {
        projectName: "",
        projectDescription: "",
        projectLogo: logo4,
        currentFunding: 1600,
        fundingGoal: 1400,
        learnButtonLink: "/4",
        giveButtonLink: "/4",
        id: 4,
    },
    {
        projectName: "",
        projectDescription: "",
        projectLogo: logo1,
        currentFunding: 1600,
        fundingGoal: 1900,
        learnButtonLink: "/5",
        giveButtonLink: "/5",
        id: 5,
    },
]

export const upcomingStartUps = [
    {
        projectName: "",
        projectDescription: "",
        projectLogo: logo3,
        currentFunding: 500,
        fundingGoal: 1000,
        learnButtonLink: "/1",
        giveButtonLink: null,
        id: 1,
    },
    {
        projectName: "",
        projectDescription: "",
        projectLogo: logo1,
        currentFunding: 13000,
        fundingGoal: 15000,
        learnButtonLink: "/2",
        giveButtonLink: null,
        id: 2,
    },
    {
        projectName: "",
        projectDescription: "",
        projectLogo: logo2,
        currentFunding: 600,
        fundingGoal: 1200,
        learnButtonLink: "/3",
        giveButtonLink: null,
        id: 3,
    },
    {
        projectName: "",
        projectDescription: "",
        projectLogo: logo1,
        currentFunding: 1800,
        fundingGoal: 1900,
        learnButtonLink: "/4",
        giveButtonLink: null,
        id: 4,
    },
    {
        projectName: "",
        projectDescription: "",
        projectLogo: logo3,
        currentFunding: 1200,
        fundingGoal: 1300,
        learnButtonLink: "/5",
        giveButtonLink: null,
        id: 5,
    },
]