export const myCourses = [
    {
        title: "Intro to Blockchain",
        description: "blockchain, cryptocurrency fundamentals",
        modulesCompleted: 7.1,
        allModules: 10,
        earn: 20,
        learnButtonLink: "/1",
        id: 1,
    },
    {
        title: "Intro to Blockchain",
        description: "blockchain, cryptocurrency fundamentals",
        modulesCompleted: 6.5,
        allModules: 10,
        earn: 10,
        learnButtonLink: "/2",
        id: 2,
    },
    {
        title: "Intro to Blockchain",
        description: "blockchain, cryptocurrency fundamentals",
        modulesCompleted: 8,
        allModules: 10,
        earn: 35,
        learnButtonLink: "/3",
        id: 3,
    },
    {
        title: "Intro to Blockchain",
        description: "blockchain, cryptocurrency fundamentals",
        modulesCompleted: 3,
        allModules: 10,
        earn: 40,
        learnButtonLink: "/4",
        id: 4,
    },
    {
        title: "Intro to Blockchain",
        description: "blockchain, cryptocurrency fundamentals",
        modulesCompleted: 4.1,
        allModules: 10,
        earn: 15,
        learnButtonLink: "/5",
        id: 5,
    },
]

export const featuredCurses = [
    {
        title: "Intro to Blockchain",
        description: "blockchain, cryptocurrency fundamentals",
        modulesCompleted: 9.8,
        allModules: 10,
        earn: 20,
        learnButtonLink: "/1",
        id: 1,
    },
    {
        title: "Intro to Blockchain",
        description: "blockchain, cryptocurrency fundamentals",
        modulesCompleted: 10,
        allModules: 10,
        earn: 30,
        learnButtonLink: "/2",
        id: 2,
    },
    {
        title: "Intro to Blockchain",
        description: "blockchain, cryptocurrency fundamentals",
        modulesCompleted: 5.8,
        allModules: 10,
        earn: 50,
        learnButtonLink: "/3",
        id: 3,
    },
    {
        title: "Intro to Blockchain",
        description: "blockchain, cryptocurrency fundamentals",
        modulesCompleted: 7.8,
        allModules: 10,
        earn: 35,
        learnButtonLink: "/4",
        id: 4,
    },
    {
        title: "Intro to Blockchain",
        description: "blockchain, cryptocurrency fundamentals",
        modulesCompleted: 1,
        allModules: 10,
        earn: 45,
        learnButtonLink: "/5",
        id: 5,
    },
]